# Generated by Django 3.0.6 on 2020-06-13 07:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=40)),
                ('departmental_lat', models.CharField(max_length=20)),
                ('departmental_lon', models.CharField(max_length=20)),
                ('departmental_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('userIp', models.GenericIPAddressField()),
                ('userPassword', models.CharField(blank=True, max_length=30)),
                ('userDepartment', models.CharField(choices=[('ComputerDepartment', 'COMPUTER DEPARTMENT'), ('AccountsDepartment', 'ACCOUNTS DEPARTMENT'), ('ProductionDepartment', 'PRODUCTION DEPARTMENT'), ('MarketingDepartment', 'MARKETING DEPARTMENT'), ('HRDepartment', 'HR DEPARTMERT')], default='ComputerDepartment', max_length=50)),
                ('userPrivcayKey', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('countAttendence', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendenceEmployee.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateField', models.DateField(default=datetime.date(2020, 6, 13))),
                ('timeField', models.TimeField(default=datetime.time(7, 12, 49, 772985))),
                ('wasPresent', models.BooleanField(default=False)),
                ('userDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendenceEmployee.UserDetails')),
            ],
        ),
    ]
