# Generated by Django 3.0.6 on 2020-06-13 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendenceEmployee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='timeField',
            field=models.TimeField(default=datetime.time(7, 12, 53, 202536)),
        ),
    ]
