# Generated by Django 3.0.6 on 2020-06-13 14:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AttendenceEmployee', '0002_auto_20200613_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='timeField',
            field=models.TimeField(default=datetime.time(14, 28, 5, 70960)),
        ),
        migrations.AlterField(
            model_name='totalattendence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userDepartment',
            field=models.CharField(choices=[('COMPUTER DEPARTMENT', 'COMPUTER DEPARTMENT'), ('ACCOUNTS DEPARTMENT', 'ACCOUNTS DEPARTMENT'), ('PRODUCTION DEPARTMENT', 'PRODUCTION DEPARTMENT'), ('MARKETING DEPARTMENT', 'MARKETING DEPARTMENT'), ('HR DEPARTMERT', 'HR DEPARTMERT')], default='COMPUTER DEPARTMENT', max_length=50),
        ),
    ]
