# Generated by Django 3.0.6 on 2020-06-13 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendenceEmployee', '0003_auto_20200613_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='userPrivcayKey',
            new_name='userPrivacyKey',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='timeField',
            field=models.TimeField(default=datetime.time(16, 54, 48, 335430)),
        ),
    ]
